@startuml
skinparam ClassAttributeIconSize 0
 
entity user {
-ユーザーID:int
-ユーザーネーム:String
-ユーザーパスワード:int
-体重:int
-身長:int
-目標:text
-作成日時:datetime
+サインアップ():boolean
+ログイン():boolean
+ログアウト():void
}
 
entity History {
-ユーザーID:int
-過去記録ID:int
-食事ID:text
-トレーニングID:int
-作成日時:datetime
+過去記録の削除():void
+食事履歴の削除():void
}
 
class food {
-ユーザーID:int
-食事ID:int
-朝食:String
-昼食:String
-夕食:String
-詳細:String
-作成日時:DateTime
-朝食カロリー:int
-昼食カロリー:int
-夕食カロリー:int
}
 
 
class training {
-ユーザーID:int
-トレーニングID:int
-パーツ:String
-エクササイズ:String
-秒数:int
-回数:int
-セット:int
-合計:int
-作成日時:datetime
-トレーニング履歴:list
+トレーニング履歴削除():void
 
}
 

 
 
 
user <|-- food ://1と0.1
user <|-- training :  //1と0.1
user <|-- History : //
 
History <|-- training ://1と1
 
food <|--History: //1と1